name: exampledart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  vector_math: ^2.1.4
  # path: ^1.8.0
  liquid:
    # When depending on this package from a real application you should use:
    #   liquid: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
